#!/usr/bin/env bash
# Generates 10 random orders per run against Services.Orders.
# Each order picks a random customer from CUSTOMER_IDS and 1..4 random products
# from PRODUCT_IDS, with quantities in 1..5. The order id is left for the server
# to generate (every run produces fresh ids).
#
# CUSTOMER_IDS and PRODUCT_IDS must match the ids in .scripts/seed_customers.sh
# and .scripts/seed_products.sh — run those first so the referenced records exist.
#
# Usage:
#   bash .scripts/generate_orders.sh
#   ORDERS_URL=http://localhost:5103 ORDER_COUNT=25 bash .scripts/generate_orders.sh

on_exit() {
  local rc=$?
  if (( rc != 0 )); then
    echo
    echo ">>> Script exited with code ${rc}"
  fi
  if [[ -t 0 && -t 1 ]]; then
    echo
    read -rp "Press Enter to close..." _ || true
  fi
  exit "${rc}"
}
trap on_exit EXIT

set -uo pipefail

BASE_URL="${ORDERS_URL:-http://localhost:5103}"
ORDER_COUNT="${ORDER_COUNT:-10}"

if ! command -v curl >/dev/null 2>&1; then
  echo "ERROR: curl is not on PATH. Install it or open a Git Bash terminal." >&2
  exit 127
fi

if ! curl -sS --max-time 3 -o /dev/null "${BASE_URL}/orders?skip=0&take=1"; then
  echo "ERROR: cannot reach ${BASE_URL}. Is Services.Orders running?" >&2
  exit 1
fi

# Keep these arrays in sync with the seed scripts.
CUSTOMER_IDS=(
  "11111111-1111-1111-1111-111111111101"
  "11111111-1111-1111-1111-111111111102"
  "11111111-1111-1111-1111-111111111103"
  "11111111-1111-1111-1111-111111111104"
  "11111111-1111-1111-1111-111111111105"
)

PRODUCT_IDS=(
  "22222222-2222-2222-2222-222222222201"
  "22222222-2222-2222-2222-222222222202"
  "22222222-2222-2222-2222-222222222203"
  "22222222-2222-2222-2222-222222222204"
  "22222222-2222-2222-2222-222222222205"
  "22222222-2222-2222-2222-222222222206"
  "22222222-2222-2222-2222-222222222207"
  "22222222-2222-2222-2222-222222222208"
  "22222222-2222-2222-2222-222222222209"
  "22222222-2222-2222-2222-222222222210"
  "22222222-2222-2222-2222-222222222211"
  "22222222-2222-2222-2222-222222222212"
  "22222222-2222-2222-2222-222222222213"
  "22222222-2222-2222-2222-222222222214"
  "22222222-2222-2222-2222-222222222215"
  "22222222-2222-2222-2222-222222222216"
  "22222222-2222-2222-2222-222222222217"
  "22222222-2222-2222-2222-222222222218"
  "22222222-2222-2222-2222-222222222219"
  "22222222-2222-2222-2222-222222222220"
)

PAYMENT_METHODS=("CreditCard" "BankTransfer" "Cash" "DebitCard")
CURRENCIES=("TRY" "USD" "EUR")

CUSTOMER_COUNT=${#CUSTOMER_IDS[@]}
PRODUCT_COUNT=${#PRODUCT_IDS[@]}

echo "Generating ${ORDER_COUNT} order(s) at ${BASE_URL} ..."

failures=0
for (( n = 1; n <= ORDER_COUNT; n++ )); do
  customer_id="${CUSTOMER_IDS[$(( RANDOM % CUSTOMER_COUNT ))]}"
  payment="${PAYMENT_METHODS[$(( RANDOM % ${#PAYMENT_METHODS[@]} ))]}"
  currency="${CURRENCIES[$(( RANDOM % ${#CURRENCIES[@]} ))]}"

  # 1..4 line items per order, sampled without replacement so the same product
  # doesn't appear twice on the same order.
  line_count=$(( RANDOM % 4 + 1 ))

  # Shuffle a copy of indices 0..PRODUCT_COUNT-1 and take the first line_count.
  indices=()
  for (( j = 0; j < PRODUCT_COUNT; j++ )); do indices+=( "$j" ); done
  for (( j = PRODUCT_COUNT - 1; j > 0; j-- )); do
    k=$(( RANDOM % (j + 1) ))
    tmp="${indices[$j]}"; indices[$j]="${indices[$k]}"; indices[$k]="$tmp"
  done

  items_json=""
  for (( j = 0; j < line_count; j++ )); do
    pid="${PRODUCT_IDS[${indices[$j]}]}"
    qty=$(( RANDOM % 5 + 1 ))
    if (( j > 0 )); then items_json+=","; fi
    items_json+="{\"productId\":\"${pid}\",\"quantity\":${qty}}"
  done

  body=$(cat <<EOF
{
  "customerId":"${customer_id}",
  "paymentMethod":"${payment}",
  "currency":"${currency}",
  "shippingAddress":"Sample shipping address",
  "billingAddress":"Sample billing address",
  "items":[${items_json}],
  "notes":"Generated by generate_orders.sh"
}
EOF
)

  status=$(curl -sS -o /tmp/generate_order_resp.json -w "%{http_code}" \
    -X POST "${BASE_URL}/orders" \
    -H "Content-Type: application/json" \
    -d "${body}") || status="000"

  case "${status}" in
    201)
      # Pluck the id out of the response for the log line. Falls back to a placeholder
      # if jq is unavailable so the script still works without it.
      if command -v jq >/dev/null 2>&1; then
        order_id=$(jq -r '.id // "?"' /tmp/generate_order_resp.json)
      else
        order_id=$(grep -oE '"id"[^"]*"[^"]+"' /tmp/generate_order_resp.json | head -1 | grep -oE '"[0-9a-f-]{36}"' | tr -d '"' || echo "?")
      fi
      echo "  [${n}/${ORDER_COUNT}] 201  customer=${customer_id:24}  items=${line_count}  ${payment}/${currency}  id=${order_id}"
      ;;
    *)
      echo "  [${n}/${ORDER_COUNT}] FAILED ${status}  customer=${customer_id:24}  items=${line_count}"
      if [[ -s /tmp/generate_order_resp.json ]]; then
        echo "    response:"
        sed 's/^/      /' /tmp/generate_order_resp.json
        echo
      fi
      failures=$(( failures + 1 ))
      ;;
  esac
done

echo
if (( failures > 0 )); then
  echo "Done with ${failures} failure(s)."
  exit 1
fi

echo "Done. ${ORDER_COUNT} order(s) created."
